### ISSUE TITLE
UnknownTimeZoneError: '/UTC'

### ISSUE THREAD

**Issue by movermeyer** [regebro/tzlocal#101]
On the `ubuntu` Docker image, the contents of `/etc/localtime` is `/UTC`, which causes tzlocal to raise:

```
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/usr/local/lib/python3.9/dist-packages/tzlocal/unix.py", line 165, in get_localzone
    _cache_tz = _get_localzone()
  File "/usr/local/lib/python3.9/dist-packages/tzlocal/unix.py", line 86, in _get_localzone
    tz = pytz.timezone(etctz.replace(' ', '_'))
  File "/usr/local/lib/python3.9/dist-packages/pytz/__init__.py", line 181, in timezone
    raise UnknownTimeZoneError(zone)
pytz.exceptions.UnknownTimeZoneError: '/UTC'
```

<details>
  <summary><b>Dockerfile that reproduces the issue</b></summary>

```dockerfile
FROM ubuntu

RUN apt-get update && \
    apt install -y software-properties-common && \
    add-apt-repository ppa:deadsnakes/ppa && \
    apt-get update

# Install Python 3
RUN apt install -y python python-dev && \
    apt install -y python3.9 python3.9-dev python3.9-venv

# Make Python3 the default `python`
RUN ln -s /usr/lib/python3.9/_sysconfigdata__linux_x86_64-linux-gnu.py  /usr/lib/python3.9/_sysconfigdata__x86_64-linux-gnu.py && \
    update-alternatives --install /usr/bin/python python /usr/bin/python3.9 10

# Install pip
RUN apt-get install -y git curl gcc build-essential && \
    curl https://bootstrap.pypa.io/get-pip.py -o get-pip.py && \
    python get-pip.py

# Get tzlocal
RUN pip install tzlocal

# Trigger the bug
RUN python -c "from tzlocal import get_localzone; tz = get_localzone()"
```

</details>

**Comment by movermeyer** [comment]
I reported this bug (?) upstream: https://bugs.launchpad.net/ubuntu/+source/tzdata/+bug/1899343

**Comment by regebro** [comment]
I added a workaround in 4.0.1.
