### ISSUE TITLE
Multiple conflicting time zone configurations

### ISSUE THREAD

**Issue by neomis** [regebro/tzlocal#122]
Running on Ubuntu 16.04 I'm getting this error with tzlocal >= 4.0.1

```
Python 3.8.3 (default, Sep  2 2020, 09:15:06) 
[GCC 5.4.0 20160609] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> from tzlocal import get_localzone
>>> get_localzone()
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/dispo/test_pytz/lib/python3.8/site-packages/tzlocal/unix.py", line 205, in get_localzone
    _cache_tz = _get_localzone()
  File "/home/dispo/test_pytz/lib/python3.8/site-packages/tzlocal/unix.py", line 167, in _get_localzone
    tzname = _get_localzone_name(_root)
  File "/home/dispo/test_pytz/lib/python3.8/site-packages/tzlocal/unix.py", line 146, in _get_localzone_name
    raise utils.ZoneInfoNotFoundError(message)
tzlocal.utils.ZoneInfoNotFoundError: 'Multiple conflicting time zone configurations found:\n/etc/timezone: America/Denver\n/etc/sysconfig/clock: America/Denver\n/usr/share/zoneinfo/Navajo: Navajo\nFix the configuration, or set the time zone in a TZ environment variable.\n'```

```
cat /etc/timezone 
America/Denver
```
```
cat /etc/sysconfig/clock
ZONE="America/Denver"
UTC=false
ARC=false
```

I don't know why it's checking /usr/share/zoneinfo/Navajo?

**Comment by D3vil0p3r** [comment]
Solved by having `/etc/localtime` pointing to a timezone that is the same in `/etc/timezone` file.
