### ISSUE TITLE
Error dealing with timezone file that has a comment in the first line

### ISSUE THREAD

**Issue by giovino** [regebro/tzlocal#27]
It does not appear get_localzone() is handling a /etc/timezone file with a comment in the first line.

## version

```
pip show tzlocal
---
Metadata-Version: 2.0
Name: tzlocal
Version: 1.2
Summary: tzinfo object for the local timezone
Home-page: https://github.com/regebro/tzlocal
Author: Lennart Regebro
Author-email: regebro@gmail.com
License: CC0 1.0 Universal
Location: /root/bin/wf-ufw/venv/lib/python2.7/site-packages
Requires: pytz
```

## Example: Failing

```
cat /etc/timezone
# Ansible
Etc/UTC
```

```
python2.7
Python 2.7.6 (default, Jun 22 2015, 17:58:13) 
[GCC 4.8.2] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> from tzlocal import get_localzone
>>> get_localzone()
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/root/bin/wf-ufw/venv/local/lib/python2.7/site-packages/tzlocal/unix.py", line 122, in get_localzone
    _cache_tz = _get_localzone()
  File "/root/bin/wf-ufw/venv/local/lib/python2.7/site-packages/tzlocal/unix.py", line 61, in _get_localzone
    return pytz.timezone(etctz.replace(' ', '_'))
  File "/root/bin/wf-ufw/venv/local/lib/python2.7/site-packages/pytz/__init__.py", line 180, in timezone
    raise UnknownTimeZoneError(zone)
pytz.exceptions.UnknownTimeZoneError: ''
>>> 
```

## Example: Working

```
cat /etc/timezone
Etc/UTC
```

```
python2.7
Python 2.7.6 (default, Jun 22 2015, 17:58:13) 
[GCC 4.8.2] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> from tzlocal import get_localzone
>>> get_localzone()
<StaticTzInfo 'Etc/UTC'>
```

**Comment by regebro** [comment]
/etc/timezone should contain the timezone only, there's no support for comments: https://bugs.openjdk.java.net/browse/JDK-7192951

**Comment by giovino** [comment]
thanks for the information!
